CREATE TABLE doctors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  specialty VARCHAR(255),
  contact VARCHAR(255),
  address VARCHAR(255),
  city VARCHAR(255),
  experience VARCHAR(50),
  rating DECIMAL(3, 1),
  image VARCHAR(255)
);

INSERT INTO doctors (name, specialty, contact, address, city, experience, rating, image) VALUES
("Dr. John Doe", "Cardiology", "johndoe@example.com", "123 Main St", "Mumbai", "10 years", 4.5, "https://example.com/doctor1.jpg"),
("Dr. Jane Smith", "Pediatrics", "janesmith@example.com", "456 Park Ave", "Delhi", "8 years", 4.2, "https://example.com/doctor2.jpg"),
("Dr. Michael Johnson", "Dermatology", "michaeljohnson@example.com", "789 Elm St", "Bengaluru", "12 years", 4.8, "https://example.com/doctor3.jpg"),
("Dr. Sarah Lee", "Orthopedics", "sarahlee@example.com", "321 Oak St", "Chennai", "15 years", 4.6, "https://example.com/doctor4.jpg"),
("Dr. David Wang", "Ophthalmology", "davidwang@example.com", "987 Maple Ave", "Hyderabad", "10 years", 4.4, "https://example.com/doctor5.jpg"),
("Dr. Emily Chen", "Gynecology", "emilychen@example.com", "654 Pine St", "Kolkata", "7 years", 4.2, "https://example.com/doctor6.jpg"),
("Dr. James Davis", "Psychiatry", "jamesdavis@example.com", "234 Cedar St", "Mumbai", "13 years", 4.7, "https://example.com/doctor7.jpg"),
("Dr. Olivia Johnson", "Cardiology", "oliviajohnson@example.com", "567 Walnut Ave", "Delhi", "9 years", 4.6, "https://example.com/doctor8.jpg"),
("Dr. Benjamin Garcia", "Pediatrics", "benjamingarcia@example.com", "890 Birch St", "Bengaluru", "11 years", 4.3, "https://example.com/doctor9.jpg"),
("Dr. Sophia Thompson", "Dermatology", "sophiathompson@example.com", "876 Oak St", "Chennai", "6 years", 4.1, "https://example.com/doctor10.jpg"),
("Dr. Daniel Kim", "Orthopedics", "danielkim@example.com", "543 Pine St", "Kolkata", "14 years", 4.9, "https://example.com/doctor11.jpg"),
("Dr. Isabella Martinez", "Ophthalmology", "isabellamartinez@example.com", "432 Maple Ave", "Mumbai", "8 years", 4.2, "https://example.com/doctor12.jpg"),
("Dr. Ethan Wilson", "Gynecology", "ethanwilson@example.com", "765 Cedar St", "Delhi", "10 years", 4.7, "https://example.com/doctor13.jpg"),
("Dr. Ava Anderson", "Psychiatry", "avaanderson@example.com", "234 Pine St", "Bengaluru", "12 years", 4.6, "https://example.com/doctor14.jpg"),
("Dr. Logan Taylor", "Cardiology", "logantaylor@example.com", "987 Oak St", "Chennai", "9 years", 4.3, "https://example.com/doctor15.jpg"),
("Dr. Chloe Adams", "Pediatrics", "chloeadams@example.com", "543 Elm St", "Kolkata", "7 years", 4.1, "https://example.com/doctor16.jpg"),
("Dr. Samuel Hernandez", "Dermatology", "samuelhernandez@example.com", "321 Cedar St", "Mumbai", "11 years", 4.9, "https://example.com/doctor17.jpg"),
("Dr. Lily Turner", "Orthopedics", "lilyturner@example.com", "654 Oak St", "Delhi", "8 years", 4.2, "https://example.com/doctor18.jpg"),
("Dr. Max Carter", "Ophthalmology", "maxcarter@example.com", "876 Elm St", "Bengaluru", "10 years", 4.7, "https://example.com/doctor19.jpg"),
("Dr. Mia Baker", "Gynecology", "miabaker@example.com", "234 Pine St", "Chennai", "12 years", 4.6, "https://example.com/doctor20.jpg"),
("Dr. Jack Johnson", "Cardiology", "jackjohnson@example.com", "345 Elm St", "Delhi", "9 years", 4.4, "https://example.com/doctor21.jpg"),
("Dr. Emma Wilson", "Pediatrics", "emmawilson@example.com", "567 Pine St", "Mumbai", "11 years", 4.7, "https://example.com/doctor22.jpg"),
("Dr. Noah Miller", "Dermatology", "noahmiller@example.com", "789 Oak St", "Bengaluru", "8 years", 4.3, "https://example.com/doctor23.jpg"),
("Dr. Mia Roberts", "Orthopedics", "miaroberts@example.com", "987 Maple Ave", "Chennai", "10 years", 4.6, "https://example.com/doctor24.jpg"),
("Dr. Ava Johnson", "Ophthalmology", "avajohnson@example.com", "654 Pine St", "Kolkata", "7 years", 4.2, "https://example.com/doctor25.jpg"),
("Dr. Samuel Wilson", "Gynecology", "samuelwilson@example.com", "321 Cedar St", "Mumbai", "11 years", 4.9, "https://example.com/doctor26.jpg"),
("Dr. Lily Adams", "Psychiatry", "lilyadams@example.com", "876 Elm St", "Delhi", "8 years", 4.2, "https://example.com/doctor27.jpg"),
("Dr. Max Smith", "Cardiology", "maxsmith@example.com", "234 Pine St", "Bengaluru", "10 years", 4.7, "https://example.com/doctor28.jpg"),
("Dr. Mia Garcia", "Pediatrics", "miagarcia@example.com", "567 Pine St", "Chennai", "12 years", 4.6, "https://example.com/doctor29.jpg"),
("Dr. Jack Chen", "Dermatology", "jackchen@example.com", "789 Oak St", "Mumbai", "9 years", 4.3, "https://example.com/doctor30.jpg");
